// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evkgiwpzslgasvuufrcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2a2dpd3B6c2xnYXN2dXVmcmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTkxNDAsImV4cCI6MjA3MDM5NTE0MH0.CeA6ob4jfxxCmxdLsSlfwkjPwTetmRwHkqNx_2X1mn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});